### ISSUE TITLE
librarian cant install mcollective and choria

### ISSUE THREAD

**Issue by ripienaar** [ripienaar/mcollective-choria#125]
In order to give a easy workflow i made it so mcollective module brings in all the core choria stuff and plugins

but those again must depend on mcollective since they use its plugin installer, so that's circular.

instead the choria module should have all the module dependencies for all the choria things and the mcollective one should have none

reported by @jamtur01

**Comment by ttres** [comment]
Is this solved? I still can see the circular dependency between modules.

**Comment by ripienaar** [comment]
Well some changes were made. If you are having issues open a new ticket is best with full description. 

But as puppet has no problem with these modules one might reasonably expect that if a puppet package manager has issues with them then the package manager has issues.
