### ISSUE TITLE
puppet agent runonce silently failing

### ISSUE THREAD

**Issue by m4ce** [ripienaar/mcollective-choria#130]
Hi,

I was trying to invoke the puppet agent via MCO and happened to see the following:

1) The mco daemon doesn't have /opt/puppetlabs/puppet/bin on its PATH
```
/opt/puppetlabs/puppet/bin/ruby /opt/puppetlabs/puppet/bin/mcollectived --config=/etc/puppetlabs/mcollective/server.cfg --pidfile=/var/run/puppetlabs/mcollective.pid --daemonize LANG=en_US.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
```

2) I enabled loglevel debug and issued the runonce action:
```
[root@foo puppetlabs]# cat mcollective.log | grep -A3 -B3 'run using the command'
D, [2017-01-06T09:21:45.429155 #7671] DEBUG -- : actionpolicy.rb:153:in `lookup_policy_file' Looking for policy in /etc/puppetlabs/mcollective/policies/puppet.policy
D, [2017-01-06T09:21:45.429318 #7671] DEBUG -- : actionpolicy.rb:38:in `parse_policy_file' Parsing policyfile for puppet: /etc/puppetlabs/mcollective/policies/puppet.policy
D, [2017-01-06T09:21:45.429792 #7671] DEBUG -- : pluginmanager.rb:80:in `[]' Returning new plugin rpcaudit_plugin with class MCollective::RPC::Logfile
D, [2017-01-06T09:21:45.434852 #7671] DEBUG -- : puppet.rb:245:in `block in <class:Puppet>' Initiating a puppet agent run using the command: puppet agent --onetime --no-daemonize --color=false --show_diff
 --verbose --splay --splaylimit 30
D, [2017-01-06T09:21:45.439802 #7671] DEBUG -- : pluginmanager.rb:83:in `[]' Returning cached plugin security_plugin with class MCollective::Security::Choria
D, [2017-01-06T09:21:45.440047 #7671] DEBUG -- : pluginmanager.rb:83:in `[]' Returning cached plugin security_plugin with class MCollective::Security::Choria
D, [2017-01-06T09:21:45.443557 #7671] DEBUG -- : pluginmanager.rb:83:in `[]' Returning cached plugin connector_plugin with class MCollective::Connector::Nats
```

The puppet agent actually never ran :( From the log, it seems that it succeeded though.

3) Instead of adjusting the path, I've changed the puppet agent command:

```
[root@foo puppetlabs]# cat /etc/puppetlabs/mcollective/plugin.d/puppet.cfg
command = /opt/puppetlabs/puppet/bin/puppet agent
[root@foo puppetlabs]#
```

4) Runonce now works.

Might be worth adding /opt/puppetlabs/puppet/bin to the mcollectived's PATH?

**Comment by m4ce** [comment]
It just occurred to me that I may have to post this issue elsewhere :)

**Comment by ripienaar** [comment]
hmm, I thought choria at first configured this correctly and then later I fixed the puppet agent and the one choria deploys has this fix in it.

I fixed it in https://github.com/puppetlabs/mcollective-puppet-agent/commit/b63facd80fd13d0624fb1938f0527591dcb4eb10 does your version of the puppet agent have that fix? might have to check you have the latest module from the forge for the puppet agent

**Comment by m4ce** [comment]
yes, I have the latest version from the forge.

```
mod 'ripienaar/mcollective_agent_puppet', '1.11.1'
```

Can also confirm looking at the .dll

```
metadata :name => "puppet",
         :description => "Run Puppet agent, get its status, and enable/disable it",
         :author => "R.I.Pienaar <rip@devco.net>",
         :license => "ASL2.0",
         :version => "1.11.1",
         :url => "http://puppetlabs.com",
         :timeout => 20
```

The fix doesn't appear to be in the module :(

**Comment by ripienaar** [comment]
shitty, looks like a release is coming soon though, meanwhile add to your hiera:

```
mcollective_agent_puppet::config:
  "command": "/opt/puppetlabs/puppet/bin/puppet agent"
```

**Comment by ripienaar** [comment]
As for mcollectived PATH, unfortunately out of my hands - the situation with the AIO PATH really is terrible.  They add `/etc/profile.d/puppet-agent.sh` but that's not enough.

I think things that need to mess around Puppet paths are minimal though so the fix in the agent is best, imagine a user writes some agent and accidentally mess around the internal ruby paths instead of systems ones etc?

**Comment by m4ce** [comment]
I agree with your line of thought.

I will keep this in Hiera until the forge mcollecttive puppet agent module is updated.

Thanks for helping out!

**Comment by ripienaar** [comment]
@MikaelSmith do you know if a mco puppet agent release is in the works?

**Comment by MikaelSmith** [comment]
One isn't specifically planned, but we could likely tag something soon. What aspect of release are you looking for (tagged, packages, included in PE)?

**Comment by ripienaar** [comment]
@MikaelSmith a tag will do though https://github.com/puppetlabs/mcollective-puppet-agent/commit/62f1f4a5185b19da54db30bb43e2f14270d1f753 and https://github.com/puppetlabs/mcollective-puppet-agent/commit/b63facd80fd13d0624fb1938f0527591dcb4eb10 would be generally useful, once tagged I will put them out via my module

**Comment by MikaelSmith** [comment]
Tracking in https://tickets.puppetlabs.com/browse/MCOP-582. Hopefully get to that next week.

**Comment by ripienaar** [comment]
awesome, somehow not getting that project as mails but thanks for sorting it out @MikaelSmith
