### ISSUE TITLE
Do validation on windows

### ISSUE THREAD

**Issue by ripienaar** [ripienaar/mcollective-choria#142]
It should work on Windows but have not had a good change to test it all after initial failures with EM.

**Comment by ripienaar** [comment]
See https://github.com/ripienaar/puppet-mcollective/issues/74

**Comment by dnlsng** [comment]
I have actually just been playing with these set of plugins on Windows a few days ago. I got it working in the end as I came across a few issues, one in mcollective-choria and another in puppet-mcollective. I'm away from a computer at the moment but I can submit an issue/PR tomorrow if that helps.

**Comment by ripienaar** [comment]
@dnlsng that would be great thanks!

**Comment by ripienaar** [comment]
Works with current master out of the box on Windows_Server-2012-R2_RTM-English-64Bit-Base-2016.12.14 (ami-ab381ed8)
