### ISSUE TITLE
Empty 'hooks:' declaration in playbook makes it fail.

### ISSUE THREAD

**Issue by zipkid** [ripienaar/mcollective-choria#166]
Having a declaration of 'hooks:' without any content (or with empty 'on_...:' line) makes the playbook run fail

    hooks:
      on_success:

Result

    $ mco playbook run playbook.yaml 
    I 08:54:48: set_fact#pre                       Starting playbook set_fact at 2017-01-27 08:54:48 +0000
    E 08:54:48: set_fact#                          Playbook set_fact failed: NoMethodError: undefined method `each' for nil:NilClass

    Summary for set_fact 0.0.1 started at 2017-01-27 08:54:48 UTC

    Overall outcome: failed
          Tasks Ran: 0
          Run Time: 0.02 seconds

**Comment by ripienaar** [comment]
I'm probably going to make this error anyway, as its not valid.  hooks is an hash, if you dont give a hash it should fail.  So will just provide a better error instead
