### ISSUE TITLE
Change the path for  certificates in a windows server

### ISSUE THREAD

**Issue by farhandiwan** [ripienaar/mcollective-choria#176]
By default the choria recipes create a  folder in C:\etc  which has the puppetlabs\mcollective\choria_security\public_cert
 we can have a variable to place that into programfiles or programdata not the root C: drive.

**Comment by farhandiwan** [comment]
Here is the  log  which shows were it  happens.

W, [2017-02-08T15:56:26.952823 #1424]  WARN -- : natswrapper.rb:90:in `block in start' Reconnected after connection failure: nats://foreman.ei.local:4222
I, [2017-02-08T15:56:26.952823 #1424]  INFO -- : natswrapper.rb:76:in `log_nats_pool' Current server pool: nats://foreman.ei.local:4222
I, [2017-02-08T16:01:50.081603 #1424]  INFO -- : choria.rb:411:in `valid_certificate?' Verified certificate /CN=farhand.mcollective/OU=mcollective against CA /CN=Puppet CA: foreman.ei.local
I, [2017-02-08T16:01:50.081603 #1424]  INFO -- : choria.rb:366:in `block in cache_client_pubcert' Saving verified pubcert for choria=farhand.mcollective in /etc/puppetlabs/mcollective/choria_security/public_certs/farhand.mcollective.pem
I, [2017-02-08T16:01:50.081603 #1424]  INFO -- : choria.rb:147:in `validrequest?' Received valid request 1e36a7ba4090527f83de117e672d615e from choria=farhand.mcollective

**Comment by ripienaar** [comment]
Thank you. That's for sure a bug it should automatically create the files along with the other default location config files. Willl take a peek thanks.

**Comment by ripienaar** [comment]
what version of windows was this? Is it possible for you to run irb on it and show me the output of `RbConfig::CONFIG['host_os']`?

**Comment by farhandiwan** [comment]
Its a windows 2012R2 box.

The variable name  value is mingw32 . Are you getting the same value in
your test setup.

Regards,
Farhan Diwan

**Comment by ripienaar** [comment]
@farhandiwan thanks, I'll have to try and reproduce

**Comment by ripienaar** [comment]
Could reproduce with a local windows 10

**Comment by ripienaar** [comment]
Ah well, oops I guess :) https://github.com/ripienaar/mcollective-choria/blob/master/lib/mcollective/security/choria.rb#L473

**Comment by ripienaar** [comment]
Thanks for the report @farhandiwan, that should be fixed now
