### ISSUE TITLE
error loading nats connector

### ISSUE THREAD

**Issue by siliconalchemy** [ripienaar/mcollective-choria#36]
Following deployment wiki:
```
error 2016/08/09 14:11:07: pluginmanager.rb:171:in `rescue in loadclass' Failed to load Mcollective::Connector::Nats: cannot load such file -- mcollective/connector/nats.rb
Error: Facter: error while resolving custom fact "mcollective": cannot load such file -- mcollective/connector/nats.rb
```

**Comment by ripienaar** [comment]
this should be a one off I think? After installing it should resolve on its own or does it prevent a puppet run? 

In the end I dont thnk these facts add much value, might just remove them due to the nasty chicken and egg they cause

**Comment by siliconalchemy** [comment]
No, it shows up on each run.  Is there a rubylib setting somewhere I can check?  I'm a bit lost in the new AIO packaging.

**Comment by ripienaar** [comment]
It should be in `/opt/puppetlabs/mcollective/plugins/mcollective/connector/nats.rb` if you didnt change anything

And I am guessing you see this line whenever you run `puppet agent --test` or..?

**Comment by siliconalchemy** [comment]
Yes the file is definitely in there and permissions look OK.  Yes, running puppet agent -t.  Is there a setting that determines where the pluginmanager.rb looks to load the connector?

**Comment by ripienaar** [comment]
your `/etc/puppetlabs/mcollective/client.cfg` should have various libdir lines, it defaults to include `libdir = /opt/puppetlabs/mcollective/plugins`

**Comment by siliconalchemy** [comment]
Ah, it was set to libdir = /opt/puppetlabs/mcollective.  I changed it to /opt/puppetlabs/mcollective/plugins and that error has now gone away.

**Comment by ripienaar** [comment]
thats strange, did you perhaps change it? I hoped this would all work by default, so want to be sure how it's that way

Perhaps I can add some code to the mcollective module to set it to that anyway to avoid this problem

**Comment by ripienaar** [comment]
defaults seem good to me:

```
[rip@dev3]% docker run -ti --rm centos:7 bash
Unable to find image 'centos:7' locally
7: Pulling from library/centos

3d60d97f3ce1: Pull complete
4f9392449c03: Pull complete
585a343e1b1a: Pull complete
3adb35bd19ee: Pull complete
Digest: sha256:643a8696ecdaacb44e9d3868fcd8168588d21a923dc58bc1c74e25c3884d82f5
Status: Downloaded newer image for centos:7
[root@286be6ef9606 /]# rpm -ivh http://yum.puppetlabs.com/el/7/PC1/x86_64/puppet-agent-1.5.3-1.el7.x86_64.rpm
Retrieving http://yum.puppetlabs.com/el/7/PC1/x86_64/puppet-agent-1.5.3-1.el7.x86_64.rpm
warning: /var/tmp/rpm-tmp.2sW61d: Header V4 RSA/SHA1 Signature, key ID 4bd6ec30: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:puppet-agent-1.5.3-1.el7         ################################# [100%]
[root@286be6ef9606 /]# grep libdir /etc/puppetlabs/mcollective/*cfg
/etc/puppetlabs/mcollective/client.cfg:libdir = /opt/puppetlabs/mcollective/plugins
/etc/puppetlabs/mcollective/client.cfg:# consult the "classic" libdirs too
/etc/puppetlabs/mcollective/client.cfg:libdir = /usr/share/mcollective/plugins
/etc/puppetlabs/mcollective/client.cfg:libdir = /usr/libexec/mcollective
/etc/puppetlabs/mcollective/server.cfg:libdir = /opt/puppetlabs/mcollective/plugins
/etc/puppetlabs/mcollective/server.cfg:# consult the "classic" libdirs too
/etc/puppetlabs/mcollective/server.cfg:libdir = /usr/share/mcollective/plugins
/etc/puppetlabs/mcollective/server.cfg:libdir = /usr/libexec/mcollective
```

**Comment by siliconalchemy** [comment]
I didn't touch it, but I was using puppet-mcollective before which might have, possibly.  Thanks for this new collection of modules, I spent hours and hours reading up about manually installing mcollective/agents etc in puppet 4 before stumbling on this.  Your MMORPG graph succinctly sums up my feelings before I came across this :)

**Comment by ripienaar** [comment]
haha awesome, these are still in Beta but feedback like this is a huge encouragement, let me know should you have any others.

I'll close this ticket and open one in the mcollective module to specifically set libdir - though I cant really do it properly because the ini module is broken, so more a note till some better way can be found.

**Comment by siliconalchemy** [comment]
Thanks :)

**Comment by siliconalchemy** [comment]
Just to follow up, I also had to fix server.cfg libdir.  I also reinstalled one of my puppetservers from scratch (uninstalled puppet-agent and puppetserver packages, wiped remaining directories, reinstalled packages) and then I didn't get this error.  So the altered libdirs must have been from another module, suspect puppet_mcollective - $site_libdir is set to /opt/puppetlabs/mcollective here:
https://github.com/voxpupuli/puppet-mcollective/blob/master/manifests/defaults.pp
