### ISSUE TITLE
Error requesting cert for choria

### ISSUE THREAD

**Issue by siliconalchemy** [ripienaar/mcollective-choria#37]
Following the deploymen wiki, the default puppetserver auth.conf doesn't seem to have any permissions for /puppet/v3/environment, only /puppet/v3/environments.

```
/etc/puppetlabs/mcollective]# mco choria request_cert

The choria application failed to run, use -v for full error backtrace details: Failed to make request to Puppet: 403: Forbidden: Forbidden request: /puppet/v3/environment/production (method :get). Please see the server logs for details.
```
Is this something I should have configured somehow otherwise in puppetserver, or should choria take care of this for me?

**Comment by ripienaar** [comment]
Are you using a puppetserver or puppet master? This is the same path puppet agent talk to so should be fine - but I only tested with puppetserver not master so perhaps some issue there

**Comment by siliconalchemy** [comment]
Yes this is puppetserver.  If I specifically add /puppet/v3/environment/production to puppetserver auth.conf then I get something different:
```
The choria application failed to run: Impossible to resolve site catalog found, cannot continue with any instances

Impossible to resolve site catalog found, cannot continue with any instances (MCollective::Util::Choria::UserError)
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria/puppet_v3_environment.rb:15:in `initialize'  <----
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb:144:in `new'
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb:144:in `puppet_environment'
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria/orchestrator.rb:14:in `initialize'
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb:153:in `new'
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb:153:in `orchestrator'
	from /opt/puppetlabs/mcollective/plugins/mcollective/application/choria.rb:177:in `orchestrator'
	from /opt/puppetlabs/mcollective/plugins/mcollective/application/choria.rb:81:in `rescue in main'
	from /opt/puppetlabs/mcollective/plugins/mcollective/application/choria.rb:78:in `main'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/application.rb:293:in `run'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/applications.rb:23:in `run'
	from /opt/puppetlabs/bin/mco:33:in `<main>'
```

**Comment by ripienaar** [comment]
Ok so you got the cert - that's weird but I will try a clean setup. The endpoint there is the one that should be in auth.conf by default

This impossible error - you get that from `mco choria plan`? Do you have any site applications setup? Puppet has a big where it lets you write impossible code there so could be related to your site catalog code in site.pp

**Comment by siliconalchemy** [comment]
I get the impossible error for any mco choria command.
My setup may be a bit of a mess.  I had a working puppet 3/passenger and  mcollective/activemq cluster setup working great, using mco puppet client/agent to run_once when commanded from web apps.  I thought I'd do an upgrade to puppet 4 - well it's taken me about 3 days so far.. puppet 4 is a major, major upgrade, looks like almost a complete rewrite.  Eventually got modules upgraded, manifests upgraded/fixed, now just need to get my mcollective puppet back up and running.
Your choria sounds like manna from heaven for people like me - the original mcollective/activemq setup was a nightmare and took quite a while to work out.  If you can work out a simple default setup of mcollective and agents using modules I'm sure it will spur greater usage.
I don't have any site applications, the only thing I'm using mcollective for is running puppet remotely.

**Comment by ripienaar** [comment]
Interesting, ok let me look into this error a bit more in the morning. Might indeed be enabling a class when I should not which might cause this. 

For sure this is optimised for a fresh setup at the moment impossible to fix a previously bad setup - well I have some ideas but that's a lot of hassle still

**Comment by ripienaar** [comment]
Ok just to confirm, this error comes from `mco choria plan` and `mco choria run` I cant imagine it comes from the `request_cert`? 

Those wont work without you setting stuff up on the puppet side - they are not for running normal puppet runs, these are specifically for the puppet 4 multi site stuff.

For normal puppet runs you need to do `mco puppet ....` as always

**Comment by siliconalchemy** [comment]
I get the same error from request_cert btw.  I've also tried this from a freshly installed and configured puppetserver and client and still get the same 403 error.

**Comment by ripienaar** [comment]
please show the backtrace

**Comment by siliconalchemy** [comment]
Weird:

```
mco choria request_cert

The choria application failed to run, use -v for full error backtrace details: Failed to make request to Puppet: 403: Forbidden: Forbidden request: /puppet/v3/environment/production (method :get). Please see the server logs for details.
```

```
mco choria request_cert -v

The choria application failed to run: Impossible to resolve site catalog found, cannot continue with any instances

Impossible to resolve site catalog found, cannot continue with any instances (MCollective::Util::Choria::UserError)
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria/puppet_v3_environment.rb:15:in `initialize'  <----
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb:144:in `new'
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb:144:in `puppet_environment'
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria/orchestrator.rb:14:in `initialize'
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb:153:in `new'
	from /opt/puppetlabs/mcollective/plugins/mcollective/util/choria.rb:153:in `orchestrator'
	from /opt/puppetlabs/mcollective/plugins/mcollective/application/choria.rb:177:in `orchestrator'
	from /opt/puppetlabs/mcollective/plugins/mcollective/application/choria.rb:81:in `rescue in main'
	from /opt/puppetlabs/mcollective/plugins/mcollective/application/choria.rb:78:in `main'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/application.rb:293:in `run'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/applications.rb:23:in `run'
	from /opt/puppetlabs/bin/mco:33:in `<main>'
```

**Comment by ripienaar** [comment]
ok

**Comment by ripienaar** [comment]
all right, that should fix the error, if you feel like hacking yours with this change https://github.com/ripienaar/mcollective-choria/pull/39 we'll get more useful errors

**Comment by ripienaar** [comment]
To be clear @siliconalchemy - all the errors here you've shown are all distractions.  It stupidly caused more errors while trying to show an error - and then showed those new errors instead.

So your actual error, is hidden thusfar, if you put in that one liner patch into your `application/choria.rb` we'll get the actual error and hopefully make some progress!

**Comment by siliconalchemy** [comment]
Aha!  So now I get:
```
mco choria request_cert
Encountered a critical error: Already have a certificate '/etc/puppetlabs/puppet/ssl/certs/infra-saturn.xxx.pem', cannot request a new one
```
This is to be expected, as puppet client has already done the cert setup with puppetmaster.  Is choria intended to require to do the initial cert setup as well?

**Comment by ripienaar** [comment]
you cant 'mco' as root, have to be a non root user.

**Comment by ripienaar** [comment]
closing this one again, existing PR should resolve these issues
