### ISSUE TITLE
Mcollective server.cfg fix for puppet agent

### ISSUE THREAD

**Issue by siliconalchemy** [ripienaar/mcollective-choria#43]
Hi, so the mcollective-puppet-agent won't actually run puppet (the runonce or runall actions) as it can't find the puppet  agent in the new location (/opt/puppetlabs/bin).  The agent simply runs 'puppet agent' but it resets the path so the custom puppetlabs path set in /etc/profile.d is ignored.  There is a simple fix, which is to add this line to mcollective server.cfg:
```
plugin.puppet.command = /opt/puppetlabs/bin/puppet agent
```
This is then read in by mcollective_agent_puppet/files/mcollective/agent/puppet.rb:
```
@puppet_command = @config.pluginconf.fetch("puppet.command", "puppet agent")
```
Ref: 
https://tickets.puppetlabs.com/browse/MCOP-496?jql=text%20~%20%22mcollective-puppet-agent%22

**Comment by ripienaar** [comment]
ah yeah, thats annoying, I put mine in my path so never noticed, thanks.

You can fix this with these modules like this via hiera:

```
mcollective_agent_puppet::server_config:
   "command": "/opt/puppetlabs/bin/puppet agent"
```

**Comment by ripienaar** [comment]
closing this one, lets chat in https://github.com/ripienaar/puppet-mcollective/issues/50, be great if you can let me know if that sorts it for you
